[package]
name = "spec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.6.0"
env_logger = "0.11.3"
libc = "0.2.154"
log = "0.4.21"
prusti-contracts = "0.2.0"
